// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: service_login_ticket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建票据
type CreateLoginTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminId int64  `protobuf:"varint,1,opt,name=adminId,proto3" json:"adminId,omitempty"` // 管理员ID，和用户ID二选一
	UserId  int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`   // 用户ID
	Ip      string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`            // 可选参数，用户客户端IP
}

func (x *CreateLoginTicketRequest) Reset() {
	*x = CreateLoginTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_login_ticket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginTicketRequest) ProtoMessage() {}

func (x *CreateLoginTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_login_ticket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginTicketRequest.ProtoReflect.Descriptor instead.
func (*CreateLoginTicketRequest) Descriptor() ([]byte, []int) {
	return file_service_login_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoginTicketRequest) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *CreateLoginTicketRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateLoginTicketRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CreateLoginTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 票据值
}

func (x *CreateLoginTicketResponse) Reset() {
	*x = CreateLoginTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_login_ticket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLoginTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoginTicketResponse) ProtoMessage() {}

func (x *CreateLoginTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_login_ticket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoginTicketResponse.ProtoReflect.Descriptor instead.
func (*CreateLoginTicketResponse) Descriptor() ([]byte, []int) {
	return file_service_login_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoginTicketResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// 查找票据
type FindLoginTicketWithValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 票据值
}

func (x *FindLoginTicketWithValueRequest) Reset() {
	*x = FindLoginTicketWithValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_login_ticket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLoginTicketWithValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLoginTicketWithValueRequest) ProtoMessage() {}

func (x *FindLoginTicketWithValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_login_ticket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLoginTicketWithValueRequest.ProtoReflect.Descriptor instead.
func (*FindLoginTicketWithValueRequest) Descriptor() ([]byte, []int) {
	return file_service_login_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *FindLoginTicketWithValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FindLoginTicketWithValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginTicket *LoginTicket `protobuf:"bytes,1,opt,name=loginTicket,proto3" json:"loginTicket,omitempty"` // 票据信息
}

func (x *FindLoginTicketWithValueResponse) Reset() {
	*x = FindLoginTicketWithValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_login_ticket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindLoginTicketWithValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLoginTicketWithValueResponse) ProtoMessage() {}

func (x *FindLoginTicketWithValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_login_ticket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLoginTicketWithValueResponse.ProtoReflect.Descriptor instead.
func (*FindLoginTicketWithValueResponse) Descriptor() ([]byte, []int) {
	return file_service_login_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *FindLoginTicketWithValueResponse) GetLoginTicket() *LoginTicket {
	if x != nil {
		return x.LoginTicket
	}
	return nil
}

var File_service_login_ticket_proto protoreflect.FileDescriptor

var file_service_login_ticket_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x1a, 0x1f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5c, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x31, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x37, 0x0a, 0x1f, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x55, 0x0a, 0x20, 0x46,
	0x69, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0b, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x32, 0xcd, 0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x11, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1c,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x18, 0x66,
	0x69, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x69,
	0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x70,
	0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x57, 0x69, 0x74, 0x68, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_login_ticket_proto_rawDescOnce sync.Once
	file_service_login_ticket_proto_rawDescData = file_service_login_ticket_proto_rawDesc
)

func file_service_login_ticket_proto_rawDescGZIP() []byte {
	file_service_login_ticket_proto_rawDescOnce.Do(func() {
		file_service_login_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_login_ticket_proto_rawDescData)
	})
	return file_service_login_ticket_proto_rawDescData
}

var file_service_login_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_login_ticket_proto_goTypes = []interface{}{
	(*CreateLoginTicketRequest)(nil),         // 0: pb.CreateLoginTicketRequest
	(*CreateLoginTicketResponse)(nil),        // 1: pb.CreateLoginTicketResponse
	(*FindLoginTicketWithValueRequest)(nil),  // 2: pb.FindLoginTicketWithValueRequest
	(*FindLoginTicketWithValueResponse)(nil), // 3: pb.FindLoginTicketWithValueResponse
	(*LoginTicket)(nil),                      // 4: pb.LoginTicket
}
var file_service_login_ticket_proto_depIdxs = []int32{
	4, // 0: pb.FindLoginTicketWithValueResponse.loginTicket:type_name -> pb.LoginTicket
	0, // 1: pb.LoginTicketService.createLoginTicket:input_type -> pb.CreateLoginTicketRequest
	2, // 2: pb.LoginTicketService.findLoginTicketWithValue:input_type -> pb.FindLoginTicketWithValueRequest
	1, // 3: pb.LoginTicketService.createLoginTicket:output_type -> pb.CreateLoginTicketResponse
	3, // 4: pb.LoginTicketService.findLoginTicketWithValue:output_type -> pb.FindLoginTicketWithValueResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_login_ticket_proto_init() }
func file_service_login_ticket_proto_init() {
	if File_service_login_ticket_proto != nil {
		return
	}
	file_models_model_login_ticket_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_login_ticket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_login_ticket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLoginTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_login_ticket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLoginTicketWithValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_login_ticket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindLoginTicketWithValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_login_ticket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_login_ticket_proto_goTypes,
		DependencyIndexes: file_service_login_ticket_proto_depIdxs,
		MessageInfos:      file_service_login_ticket_proto_msgTypes,
	}.Build()
	File_service_login_ticket_proto = out.File
	file_service_login_ticket_proto_rawDesc = nil
	file_service_login_ticket_proto_goTypes = nil
	file_service_login_ticket_proto_depIdxs = nil
}
